Auto-sync dotfiles from alp-t14 on 2025-07-17 16:45:15

diff --git a/.scripts/awesome-conf b/.scripts/awesome-conf
--- a/.scripts/awesome-conf
+++ b/.scripts/awesome-conf
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# This script loads back the default Awesome WM config in case something goes wrong.
+# This script loads an Awesome WM config
 #
 
 
@@ -9,29 +9,28 @@
 # Default action
 default() {
     echo "Loading back default Awesome config from ~/.config/awesome-default (default-action)"
-    scp -vr ~/.config/awesome-backup ~/.config/awesome
+    srsync -av --exclude='.git' ~/.config/awesome-backup ~/.config/awesome
 }
 
 # Action B
 current() {
     echo "Loading the currently worked on Awesome config from ~/.config/awesome-current"
-    scp -vr ~/.config/awesome-current ~/.config/awesome
+    rsync -av --exclude='.git' ~/.config/awesome-current ~/.config/awesome
 }
 
 # Action C with config name input
 load() {
     local config_name="$1"
-    local file_path="~/.config/awesome-${config_name}"
+    local dir_path="~/.config/awesome-${config_name}"
 
     # Check if file exists
-    if [[ ! -f "$file_path" ]]; then
-        echo "Error: File '$file_path' does not exist" >&2
+    if [[ ! -d "$dir_path" ]]; then
+        echo "Error: Directory '$dir_path' does not exist" >&2
         exit 1
     fi
 
     echo "Loading the desired Awesome config from $filepath"
-    # Add your Action C code here that works with the file
-    scp -vr $file_path ~/.config/awesome
+    rsync -av --exclude='.git' $dir_path ~/.config/awesome
 }
 
 # Display usage information
